-- ============================================================================
-- MegaPool — Supabase schema
-- ============================================================================
-- Run this once in your Supabase project's SQL Editor (Project → SQL Editor →
-- New query → paste → Run). Safe to re-run: every statement is idempotent.
--
-- What this creates:
--   - public.mega_accounts  one row per MEGA account a user has connected
--   - public.pool_files     one row per file uploaded into that user's pool
--   - Row Level Security (RLS) on both tables, so a row is only ever visible
--     to the auth.users row that owns it (auth.uid() = user_id)
--
-- Note on how the app actually talks to these tables: the MegaPool server
-- uses your SUPABASE_SERVICE_ROLE_KEY for all reads/writes, which bypasses
-- RLS by design (Supabase's service role always does) — the server enforces
-- per-user scoping itself, by hand, on every query using the caller's
-- verified user id. The RLS policies below are still real security, not
-- decoration: they mean the anon/publishable key (the one safe to ship to
-- the browser) can NEVER read or write another user's rows, even if someone
-- tried to query these tables directly from the client with a stolen or
-- forged request — the database itself refuses it. Keep the service role
-- key server-side only; never send it to the browser.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Table: mega_accounts
-- One row per MEGA account a user has connected to their pool. The MEGA
-- account password is stored AES-256-GCM encrypted (see src/crypto.js),
-- keyed off the server's MASTER_KEY env var — so even someone with raw
-- database access (e.g. via the service role key) cannot read the plaintext
-- MEGA password without also having that separate secret.
-- ---------------------------------------------------------------------------
create table if not exists public.mega_accounts (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references auth.users (id) on delete cascade,
  label              text not null,
  email              text not null,
  password_encrypted text not null,
  added_at           timestamptz not null default now(),
  constraint mega_accounts_user_label_unique unique (user_id, label)
);

create index if not exists mega_accounts_user_id_idx on public.mega_accounts (user_id);

alter table public.mega_accounts enable row level security;
-- Belt-and-braces: force RLS even for the table owner role (service role still
-- bypasses RLS entirely regardless — this only affects non-service Postgres roles).
alter table public.mega_accounts force row level security;

drop policy if exists "mega_accounts_select_own" on public.mega_accounts;
create policy "mega_accounts_select_own"
  on public.mega_accounts for select
  using (auth.uid() = user_id);

drop policy if exists "mega_accounts_insert_own" on public.mega_accounts;
create policy "mega_accounts_insert_own"
  on public.mega_accounts for insert
  with check (auth.uid() = user_id);

-- Deliberately no UPDATE or DELETE policy: once an account joins a user's
-- pool it stays part of it permanently (matches the app's own business
-- rule — see the comment in src/routes/accounts.js). With no policy for
-- those actions, RLS blocks them outright for every non-service-role caller.

-- ---------------------------------------------------------------------------
-- Table: pool_files
-- One row per logical file in a user's pool. `chunks` records exactly which
-- MEGA account + node id each piece of the file lives on, so downloads can
-- be reassembled in order.
-- ---------------------------------------------------------------------------
create table if not exists public.pool_files (
  id                text primary key,             -- nanoid, generated by the app
  user_id           uuid not null references auth.users (id) on delete cascade,
  name              text not null,
  size              bigint not null default 0,
  chunks            jsonb not null default '[]'::jsonb,
  share_token       text unique,
  share_created_at  timestamptz,
  share_expires_at  timestamptz,
  created_at        timestamptz not null default now()
);

create index if not exists pool_files_user_id_idx on public.pool_files (user_id);
create index if not exists pool_files_share_token_idx on public.pool_files (share_token);

alter table public.pool_files enable row level security;
alter table public.pool_files force row level security;

drop policy if exists "pool_files_select_own" on public.pool_files;
create policy "pool_files_select_own"
  on public.pool_files for select
  using (auth.uid() = user_id);

drop policy if exists "pool_files_insert_own" on public.pool_files;
create policy "pool_files_insert_own"
  on public.pool_files for insert
  with check (auth.uid() = user_id);

drop policy if exists "pool_files_update_own" on public.pool_files;
create policy "pool_files_update_own"
  on public.pool_files for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "pool_files_delete_own" on public.pool_files;
create policy "pool_files_delete_own"
  on public.pool_files for delete
  using (auth.uid() = user_id);

-- Note on public share links: the /share/:token download route is
-- intentionally unauthenticated (that's the point of a share link), but it
-- is served entirely by the backend using the service role key — it never
-- exposes share lookups to the anon key directly, so there is no need (and
-- deliberately no policy) allowing anon/public SELECT on pool_files here.

-- ============================================================================
-- Required manual step (not SQL): enable email confirmations
-- ============================================================================
-- In the Supabase dashboard: Authentication → Providers → Email →
-- enable "Confirm email". This is what makes new sign-ups receive a
-- verification email before they can sign in; it's a project setting, not
-- something a SQL script can toggle.
-- ============================================================================
