services:
  - type: web
    name: megapool
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: MASTER_KEY
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: CHUNK_MAX_BYTES
        value: "4294967296"
      - key: NODE_ENV
        value: production
    disk:
      name: megapool-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
